---

on:
  schedule:
    - cron: '0 20 19 4 6' # http://crontab.guru
jobs:
  make-private:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo edit ${{ github.repository }} --visibility public
        env:
          GH_TOKEN: ${{ secrets.MAKE_REPO_PUBLIC }}
